server:
  port: 8084

spring:
  application:
    name: notification-service
  redis:
    host: localhost
    port: 6379
    password: ""  # Set if Redis requires authentication

  data:
    mongodb:
      uri: mongodb://admin:adminpass@localhost:27017/user_db?authSource=admin

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true

