server:
  port: 8083

spring:
  application:
    name: user-service
  data:
    mongodb:
      uri: mongodb://admin:adminpass@localhost:27017/auth_db?authSource=admin

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
