server:
  port: 8082

spring:
  application:
    name: api-gateway
  redis:
    host: localhost
    port: 6379
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/api/auth/**
          filters:
            - name: CircuitBreaker
              args:
                name: authServiceCircuitBreaker
                fallbackUri: forward:/fallback/auth-service
            - name: Retry
              args:
                retries: 3
                statuses:
                  - INTERNAL_SERVER_ERROR
                  - SERVICE_UNAVAILABLE
                backoff:
                  firstBackoff: 50ms
                  maxBackoff: 200ms
            - name: RequestRateLimiter
              args:
                redisRateLimiter.replenishRate: 10
                redisRateLimiter.burstCapacity: 20
                keyResolver: "#{@userKeyResolver}"
            - name: TimeLimiter
              args:
                configName: authServiceTimeLimiter
            - name: Bulkhead
              args:
                configName: authServiceBulkhead

        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/users/**
          filters:
            - name: CircuitBreaker
              args:
                name: userServiceCircuitBreaker
                fallbackUri: forward:/fallback/user-service
            - name: Retry
              args:
                retries: 3
                statuses:
                  - INTERNAL_SERVER_ERROR
                  - SERVICE_UNAVAILABLE
                backoff:
                  firstBackoff: 50ms
                  maxBackoff: 200ms
            - name: RequestRateLimiter
              args:
                redisRateLimiter.replenishRate: 10
                redisRateLimiter.burstCapacity: 20
                keyResolver: "#{@userKeyResolver}"
            - name: TimeLimiter
              args:
                configName: userServiceTimeLimiter
            - name: Bulkhead
              args:
                configName: userServiceBulkhead

        - id: notification-service
          uri: lb://NOTIFICATION-SERVICE
          predicates:
            - Path=/api/notifications/**
          filters:
            - name: CircuitBreaker
              args:
                name: notificationServiceCircuitBreaker
                fallbackUri: forward:/fallback/notification-service
            - name: Retry
              args:
                retries: 3
                statuses:
                  - INTERNAL_SERVER_ERROR
                  - SERVICE_UNAVAILABLE
                backoff:
                  firstBackoff: 50ms
                  maxBackoff: 200ms
            - name: RequestRateLimiter
              args:
                redisRateLimiter.replenishRate: 10
                redisRateLimiter.burstCapacity: 20
                keyResolver: "#{@userKeyResolver}"
            - name: TimeLimiter
              args:
                configName: notificationServiceTimeLimiter
            - name: Bulkhead
              args:
                configName: notificationServiceBulkhead

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

jwt:
  secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
  expiration: 86400000

resilience4j:
  circuitbreaker:
    instances:
      authServiceCircuitBreaker:
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
      userServiceCircuitBreaker:
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 5s
      notificationServiceCircuitBreaker:
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 5s

  timelimiter:
    instances:
      authServiceTimeLimiter:
        timeoutDuration: 2s
      userServiceTimeLimiter:
        timeoutDuration: 3s
      notificationServiceTimeLimiter:
        timeoutDuration: 3s

  bulkhead:
    instances:
      authServiceBulkhead:
        maxConcurrentCalls: 10
        maxWaitDuration: 1s
      userServiceBulkhead:
        maxConcurrentCalls: 20
        maxWaitDuration: 1s
      notificationServiceBulkhead:
        maxConcurrentCalls: 15
        maxWaitDuration: 1s
